AWSTemplateFormatVersion: "2010-09-09"
Description: "Create a CodePipeline pipeline with a CodeCommit repository as the source"

Parameters:
  Branch:
    AllowedPattern: "(?!^\\\\.)(?!^/)(?=^.{1,256}$)^[a-z0-9-]*/?[a-z0-9-]*$(?<!\\\\.$)(?<!/$)"
    ConstraintDescription: "Branch must be a valid git branch. Allowed pattern: (?!^\\\\.)(?!^/)(?=^.{1,256}$)^[a-z0-9-]*/?[a-z0-9-]*$(?<!\\\\.$)(?<!/$)"
    Description: "The git branch, e.g. master"
    Type: "String"
  S3BucketNameArtifacts:
    AllowedPattern: "(?=^.{3,63}$)(?!^(\\\\d+\\\\.){3}\\\\d+$)^(([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])\\\\.)*([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])$"
    ConstraintDescription: "S3BucketNameArtifacts must be a valid S3 bucket name. Allowed pattern: (?=^.{3,63}$)(?!^(\\\\d+\\\\.){3}\\\\d+$)^(([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])\\\\.)*([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])$"
    Description: "The S3 artifacts bucket name, e.g. artifacts.example.com"
    Type: "String"
  RepositoryName:
    AllowedPattern: "^[a-zA-Z0-9._-]{1,100}$(?<!\\\\.git)"
    ConstraintDescription: "RepositoryName must be a valid CodeCommit repository name. Allowed pattern: [a-zA-Z0-9._-]{1,100}$(?<!\\\\.git)"
    Description: "The CodeCommit repository name, e.g. example"
    Type: "String"

Resources:
  S3BucketArtifacts:
    Properties:
      BucketName: !Ref "S3BucketNameArtifacts"
    Type: "AWS::S3::Bucket"
  IamRoleCodePipeline:
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
      Path: "/"
    Type: "AWS::IAM::Role"
  CodePipelinePipeline:
    DependsOn:
      - "IamRoleCodePipeline"
      - "S3BucketArtifacts"
    Properties:
      ArtifactStore:
        Location: !Ref "S3BucketArtifacts"
        Type: "S3"
      RoleArn: !GetAtt "IamRoleCodePipeline.Arn"
      Stages:
        - Actions:
            - ActionTypeId:
                Category: "Source"
                Owner: "AWS"
                Version: "1"
                Provider: "CodeCommit"
              Configuration:
                BranchName: !Ref "Branch"
                RepositoryName: !Ref "RepositoryName"
              Name: "Source"
              OutputArtifacts:
                - Name: "Source"
              RunOrder: 1
          Name: "Source"
        - Actions:
            - ActionTypeId:
                Category: "Approval"
                Owner: "AWS"
                Version: "1"
                Provider: "Manual"
              InputArtifacts: []
              Name: "Approve"
              OutputArtifacts: []
              RunOrder: 1
          Name: "Approve"
    Type: "AWS::CodePipeline::Pipeline"

Outputs:
  CodePipelinePipelineName:
    Description: "CodePipeline Pipeline Name"
    Value: !Ref "CodePipelinePipeline"
  CodePipelinePipelineVersion:
    Description: "CodePipeline Pipeline Version"
    Value: !GetAtt "CodePipelinePipeline.Version"
  IamRoleCodePipelineArn:
    Description: "IAM Role CodePipeline ARN"
    Value: !GetAtt "IamRoleCodePipeline.Arn"
  IamRoleCodePipelineName:
    Description: "IAM Role CodePipeline Name"
    Value: !Ref "IamRoleCodePipeline"
  IamRoleCodePipelineRoleId:
    Description: "IAM Role CodePipeline Role Id"
    Value: !GetAtt "IamRoleCodePipeline.RoleId"
  S3BucketArtifactsArn:
    Description: "S3 Bucket Artifacts ARN"
    Value: !GetAtt "S3BucketArtifacts.Arn"
  S3BucketArtifactsDomainName:
    Description: "S3 Bucket Artifacts Domain Name"
    Value: !GetAtt "S3BucketArtifacts.DomainName"
  S3BucketArtifactsDualStackDomainName:
    Description: "S3 Bucket Artifacts Dual Stack Domain Name"
    Value: !GetAtt "S3BucketArtifacts.DualStackDomainName"
  S3BucketArtifactsName:
    Description: "S3 Bucket Artifacts Name"
    Value: !Ref "S3BucketArtifacts"
  S3BucketArtifactsRegionalDomainName:
    Description: "S3 Bucket Artifacts Regional Domain Name"
    Value: !GetAtt "S3BucketArtifacts.RegionalDomainName"
  S3BucketArtifactsWebsiteURL:
    Description: "S3 Bucket Artifacts Website URL"
    Value: !GetAtt "S3BucketArtifacts.WebsiteURL"
